package fabric

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"strings"
	"unicode"
	"unicode/utf8"

	"fabric-workspace-fs/internal/fserrors"

	"github.com/microsoft/fabric-sdk-go/fabric/core"
	"github.com/microsoft/fabric-sdk-go/fabric/environment"
	"github.com/microsoft/fabric-sdk-go/fabric/lakehouse"
	"github.com/microsoft/fabric-sdk-go/fabric/notebook"
)

const maxMutationResponseBytes int64 = 1 << 20

// The platform part is optional on creation and must be generated by Fabric.
// https://learn.microsoft.com/rest/api/fabric/articles/item-management/definitions/notebook-definition
const emptyNotebookContent = `{"nbformat":4,"nbformat_minor":5,"cells":[],"metadata":{"kernelspec":{"name":"python3","language":"python","display_name":"Python 3"},"language_info":{"name":"python"}}}`

// CreateItem creates a Notebook, Lakehouse, or Environment in a workspace or
// folder. displayName is the decoded Fabric name, not a filesystem path.
//
// The SDK supplies the request models; the origin-bound transport and guarded
// polling keep credentials, response bounds, and write retries under our control.
// https://learn.microsoft.com/rest/api/fabric/notebook/items/create-notebook
// https://learn.microsoft.com/rest/api/fabric/lakehouse/items/create-lakehouse
// https://learn.microsoft.com/rest/api/fabric/environment/items/create-environment
func (c *Client) CreateItem(ctx context.Context, workspace, kind, displayName, folderID string) (Item, error) {
	if err := c.readyCreate(ctx, workspace, displayName, folderID); err != nil {
		return Item{}, err
	}
	var folder *string
	if folderID != "" {
		folder = &folderID
	}
	var collection string
	var request any
	switch kind {
	case "Notebook":
		collection = "notebooks"
		format, path := "ipynb", "notebook-content.ipynb"
		payload := base64.StdEncoding.EncodeToString([]byte(emptyNotebookContent))
		payloadType := notebook.PayloadTypeInlineBase64
		request = notebook.CreateNotebookRequest{
			DisplayName: &displayName, FolderID: folder,
			Definition: &notebook.Definition{
				Format: &format,
				Parts: []notebook.DefinitionPart{{
					Path: &path, Payload: &payload, PayloadType: &payloadType,
				}},
			},
		}
	case "Lakehouse":
		if err := validateLakehouseCreateName(displayName); err != nil {
			return Item{}, err
		}
		collection = "lakehouses"
		request = lakehouse.CreateLakehouseRequest{DisplayName: &displayName, FolderID: folder}
	case "Environment":
		collection = "environments"
		request = environment.CreateEnvironmentRequest{DisplayName: &displayName, FolderID: folder}
	default:
		return Item{}, fserrors.ErrUnsupported
	}
	body, err := json.Marshal(request)
	if err != nil {
		return Item{}, fmt.Errorf("encode Fabric create request: %w", err)
	}
	ctx, cancel := context.WithTimeout(ctx, c.operationTimeout)
	defer cancel()
	resp, err := c.createOperation(ctx, c.http.URL("/v1/workspaces/"+workspace+"/"+collection, nil), body)
	if err != nil {
		return Item{}, err
	}
	item, err := c.readMutationItem(resp, workspace)
	if err != nil {
		return Item{}, err
	}
	if item.Type != kind || item.DisplayName != displayName || !strings.EqualFold(item.FolderID, folderID) {
		return Item{}, invalidResponse("created item does not match the requested type, name, or folder")
	}
	return item, nil
}

// CreateFolder creates an ordinary Fabric folder; it does not interpret item
// suffixes. An empty parentFolderID selects the workspace root.
// https://learn.microsoft.com/rest/api/fabric/core/folders/create-folder
func (c *Client) CreateFolder(ctx context.Context, workspace, displayName, parentFolderID string) (Folder, error) {
	if err := c.readyCreate(ctx, workspace, displayName, parentFolderID); err != nil {
		return Folder{}, err
	}
	if err := validateFolderCreateName(displayName); err != nil {
		return Folder{}, err
	}
	request := core.CreateFolderRequest{DisplayName: &displayName}
	if parentFolderID != "" {
		request.ParentFolderID = &parentFolderID
	}
	body, err := json.Marshal(request)
	if err != nil {
		return Folder{}, fmt.Errorf("encode Fabric folder create request: %w", err)
	}
	ctx, cancel := context.WithTimeout(ctx, c.operationTimeout)
	defer cancel()
	resp, err := c.http.Request(ctx, http.MethodPost, c.http.URL("/v1/workspaces/"+workspace+"/folders", nil), operationHeaders(body), body, false)
	if err != nil {
		return Folder{}, err
	}
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		return Folder{}, mutationUnexpectedResponse(resp)
	}
	folder, err := c.readMutationFolder(resp, workspace)
	if err != nil {
		return Folder{}, err
	}
	if folder.DisplayName != displayName || !strings.EqualFold(folder.ParentFolderID, parentFolderID) {
		return Folder{}, invalidResponse("created folder does not match the requested name or parent")
	}
	return folder, nil
}

// DeleteItem uses the public item's default deletion behavior (soft deletion
// where supported). It never requests hard deletion or retries a failed write.
// The caller must enforce ownership and emptiness before calling this method.
// https://learn.microsoft.com/rest/api/fabric/core/items/delete-item
func (c *Client) DeleteItem(ctx context.Context, workspace, itemID string) error {
	return c.deleteMutation(ctx, workspace, "items", itemID)
}

// DeleteFolder deletes an empty folder. Fabric rejects folders containing items
// or nested folders with FolderNotEmpty; this is not a recursive-delete API.
// The caller should also preflight emptiness, including any local overlay.
// https://learn.microsoft.com/rest/api/fabric/core/folders/delete-folder
func (c *Client) DeleteFolder(ctx context.Context, workspace, folderID string) error {
	return c.deleteMutation(ctx, workspace, "folders", folderID)
}

func (c *Client) deleteMutation(ctx context.Context, workspace, collection, id string) error {
	if err := c.ready(ctx, workspace, id); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(ctx, c.operationTimeout)
	defer cancel()
	resp, err := c.http.Request(ctx, http.MethodDelete, c.http.URL("/v1/workspaces/"+workspace+"/"+collection+"/"+id, nil), jsonHeaders(), nil, false)
	if err != nil {
		return err
	}
	// Both public DELETE contracts document 200, not an accepted operation.
	if resp.StatusCode != http.StatusOK {
		return mutationUnexpectedResponse(resp)
	}
	_, err = readResponse(resp, min(c.maxDefinitionBytes, maxMutationResponseBytes))
	return err
}

// GetItem reads and verifies an item's immutable ID without resolving its name.
// https://learn.microsoft.com/rest/api/fabric/core/items/get-item
func (c *Client) GetItem(ctx context.Context, workspace, itemID string) (Item, error) {
	if err := c.ready(ctx, workspace, itemID); err != nil {
		return Item{}, err
	}
	ctx, cancel := context.WithTimeout(ctx, c.operationTimeout)
	defer cancel()
	resp, err := c.http.Request(ctx, http.MethodGet, c.http.URL("/v1/workspaces/"+workspace+"/items/"+itemID, nil), jsonHeaders(), nil, true)
	if err != nil {
		return Item{}, err
	}
	if resp.StatusCode != http.StatusOK {
		return Item{}, mutationUnexpectedResponse(resp)
	}
	item, err := c.readMutationItem(resp, workspace)
	if err != nil {
		return Item{}, err
	}
	if !strings.EqualFold(item.ID, itemID) {
		return Item{}, invalidResponse("item ID does not match the request")
	}
	return item, nil
}

// GetFolder reads and verifies a folder's immutable ID.
// https://learn.microsoft.com/rest/api/fabric/core/folders/get-folder
func (c *Client) GetFolder(ctx context.Context, workspace, folderID string) (Folder, error) {
	if err := c.ready(ctx, workspace, folderID); err != nil {
		return Folder{}, err
	}
	ctx, cancel := context.WithTimeout(ctx, c.operationTimeout)
	defer cancel()
	resp, err := c.http.Request(ctx, http.MethodGet, c.http.URL("/v1/workspaces/"+workspace+"/folders/"+folderID, nil), jsonHeaders(), nil, true)
	if err != nil {
		return Folder{}, err
	}
	if resp.StatusCode != http.StatusOK {
		return Folder{}, mutationUnexpectedResponse(resp)
	}
	folder, err := c.readMutationFolder(resp, workspace)
	if err != nil {
		return Folder{}, err
	}
	if !strings.EqualFold(folder.ID, folderID) {
		return Folder{}, invalidResponse("folder ID does not match the request")
	}
	return folder, nil
}

func (c *Client) readyCreate(ctx context.Context, workspace, name, parentID string) error {
	if err := c.ready(ctx, workspace); err != nil {
		return err
	}
	if parentID != "" {
		if err := ValidateID(parentID); err != nil {
			return err
		}
	}
	return validateCreateName(name)
}

func validateCreateName(name string) error {
	if !utf8.ValidString(name) || strings.TrimSpace(name) == "" || name == "." || name == ".." {
		return fmt.Errorf("invalid Fabric display name: %w", fs.ErrInvalid)
	}
	for _, r := range name {
		if unicode.IsControl(r) {
			return fmt.Errorf("invalid Fabric display name: %w", fs.ErrInvalid)
		}
	}
	return nil
}

func validateLakehouseCreateName(name string) error {
	// https://learn.microsoft.com/fabric/data-engineering/create-lakehouse
	if len(name) == 0 || len(name) > 123 || !asciiLetter(name[0]) {
		return fmt.Errorf("invalid Fabric lakehouse name: %w", fs.ErrInvalid)
	}
	for _, r := range name {
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_') {
			return fmt.Errorf("invalid Fabric lakehouse name: %w", fs.ErrInvalid)
		}
	}
	return nil
}

func asciiLetter(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

func validateFolderCreateName(name string) error {
	// These are Fabric's folder rules, not Windows filename restrictions.
	// https://learn.microsoft.com/fabric/fundamentals/workspaces-folders#folder-name-requirements
	if utf8.RuneCountInString(name) > 255 || name != strings.Trim(name, " ") ||
		strings.ContainsAny(name, "~\"#.&*:<>?/{|}") {
		return fmt.Errorf("invalid Fabric folder name: %w", fs.ErrInvalid)
	}
	switch strings.ToLower(name) {
	case "$recycle.bin", "recycled", "recycler":
		return fmt.Errorf("reserved Fabric folder name: %w", fs.ErrInvalid)
	}
	return nil
}

func (c *Client) readMutationItem(resp *http.Response, workspace string) (Item, error) {
	var wire struct {
		Item
		WorkspaceID *string `json:"workspaceId"`
		FolderID    *string `json:"folderId"`
	}
	if err := readJSON(resp, min(c.maxDefinitionBytes, maxMutationResponseBytes), &wire); err != nil {
		return Item{}, err
	}
	if err := mutationWorkspace(wire.WorkspaceID, workspace); err != nil {
		return Item{}, err
	}
	if wire.FolderID != nil {
		if ValidateID(*wire.FolderID) != nil {
			return Item{}, invalidResponse("invalid item folder ID")
		}
		wire.Item.FolderID = *wire.FolderID
	}
	if err := validItem(wire.Item); err != nil {
		return Item{}, err
	}
	return wire.Item, nil
}

func (c *Client) readMutationFolder(resp *http.Response, workspace string) (Folder, error) {
	var wire struct {
		Folder
		WorkspaceID    *string `json:"workspaceId"`
		ParentFolderID *string `json:"parentFolderId"`
	}
	if err := readJSON(resp, min(c.maxDefinitionBytes, maxMutationResponseBytes), &wire); err != nil {
		return Folder{}, err
	}
	if err := mutationWorkspace(wire.WorkspaceID, workspace); err != nil {
		return Folder{}, err
	}
	if wire.ParentFolderID != nil {
		if ValidateID(*wire.ParentFolderID) != nil {
			return Folder{}, invalidResponse("invalid parent folder ID")
		}
		wire.Folder.ParentFolderID = *wire.ParentFolderID
	}
	if err := validFolder(wire.Folder); err != nil {
		return Folder{}, err
	}
	if strings.EqualFold(wire.Folder.ID, wire.Folder.ParentFolderID) {
		return Folder{}, invalidResponse("folder is its own parent")
	}
	return wire.Folder, nil
}

func mutationWorkspace(actual *string, expected string) error {
	if actual != nil && (ValidateID(*actual) != nil || !strings.EqualFold(*actual, expected)) {
		return invalidResponse("workspace ID does not match the request")
	}
	return nil
}
